name: TPA-1503
favicon: null
layout_spectrum: 0.4989
typography_spectrum: 0.45156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbd8d3'
    - '#928f8a'
    - '#8b2926'
    - '#3a3633'
    - '#825850'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.1768787989858538
purpose: []
